### ISSUE TITLE
Release 2.0.0 to npm

### ISSUE THREAD

**Issue by eps1lon** [codemodsquad/jscodeshift-find-imports#16]
[2.0.0](https://github.com/codemodsquad/jscodeshift-find-imports/releases/tag/v2.0.0) was released on GitHub but [npm doesn't include it](https://www.npmjs.com/package/jscodeshift-find-imports). 

/cc @jedwards1211 
When `jscodeshift-find-imports` is released on npm can we at the same time update `jscodeshift-add-imports`.

Right now `jscodeshift-add-imports` pulls in an older version of `ast-types` that I'd like to get rid of.

**Comment by jedwards1211** [comment]
Okay, something must have thrown off semantic-release, I'll see if I can sort this out and upgrade ast-types as well.

**Comment by jedwards1211** [comment]
Actually I'm confused what you mean, I see 2.0.0 on npm via the website and `npm view jscodeshift-find-imports version`...maybe there was some wacky npm glitch?

**Comment by eps1lon** [comment]
Maybe I confused it with `jscodeshift-add-imports`. The issue about `ast-types` remains. `jscodeshift` is currently multiple versions behind in `jscodeshift-find-imports`

**Comment by jedwards1211** [comment]
I think what you meant is that `jscodeshift-add-imports` wasn't using version 2 of `jscodeshift-find-imports`.  I released new versions of both though with `jscodeshift` 0.11.0 (really wish people would stop using version 0...).  Can you upgrade and confirm that everything is fixed for you?  You should get `ast-types@0.12.1` now.

Btw sometimes with yarn at least to ensure I get the latest version of a transitive dep, I have to remove the primary deps and then add them back, `yarn upgrade --latest` doesn't always upgrade the transitive deps.

**Comment by jedwards1211** [comment]
argh hang on, I accidentally published `jscodeshift-find-imports` with `@types/jscodeshift` as a dev dep

**Comment by jedwards1211** [comment]
Actually I think `ast-types` should be `0.14.1` if all the transitive deps work correctly, but I'm running into this issue: https://github.com/benjamn/ast-types/issues/425

**Comment by jedwards1211** [comment]
Do you know if `ast-types@0.13.4` will work for you?

**Comment by eps1lon** [comment]
In 0.x any minor bump is considered breaking so package managers won't pull in 0.11 if you declare `^0.6`. You have to declare `^0.11`. So removing the lockfile entries wouldn't have done anything here.

While I don't think you should ever use `>=` it should fix my specific problem. Will check back tomorrow.

**Comment by jedwards1211** [comment]
I guess I should use `^0.7.0 || ^0.8.0 || ...`.  0.x packages are so inconvenient to work with...I was worried if I left `jscodeshift` as a primary dependency it might cause other issues?
I did that in `jscodeshift-add-imports` for 0.7.x up to 0.10.x since it breaks with jscodeshift 0.11.0.

**Comment by jedwards1211** [comment]
Can't tell if the following releases actually contain breaking changes or not:

![image](https://user-images.githubusercontent.com/1448194/95270936-407fb480-0802-11eb-97e2-8ed214d05190.png)

Changelogs are virtually guaranteed to be low quality if you're not using some kind of automation like `semantic-release`...

**Comment by jedwards1211** [comment]
forgot to close this
